# -*- mode: ruby -*-
# vi: set ft=ruby :

#Global Variables
CHEF_SERVER_PROTOCOL="https"
CHEF_SERVER_IP="192.168.50.2"
CHEF_SERVER_PORT="4000"
VAGRANTFILE_API_VERSION = "2"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vbguest.auto_update = false # Required to disable automatic update of guest additions
	config.ssh.forward_agent = true	
	
	config.vm.provider "virtualbox" do |vb|
		vb.customize [
			"modifyvm", :id,
			"--nictype1", "Am79C973",
			"--ioapic", "on",
			"--rtcuseutc", "on",
			"--cpus", "2",
			"--memory", "1024"
		]
		#vb.gui = true
	end
	
	#Disable firewall (firewall rules would need added for production)
	config.vm.provision "shell", inline: "service iptables stop"
	
	# If you've authenticated to a previous chef-server that no longer has your node record, or if you get error 401, run this first
	# error 401     - your client and/or node was authenticated to a previous chef server, the new chef server has no record of your client/node 
	# error 403/409 - your client and/or node already exist in chef server, remove them and run command below to re-authenticate
	config.vm.provision "shell", inline: "if [ ! -f /tmp/rekey ]; then touch /tmp/rekey; rm -f /etc/chef/*; echo "REKEY: deleted previous keys"; fi"
	
	
	config.vm.define "testc" do |testc|
		testc.vm.host_name = "testc"
		testc.vm.box = "centos64_64"	
		testc.vm.box_url = "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.4.box"	
		
		#Network port forwards
		testc.vm.network "private_network", ip: "192.168.50.3"
		
		testc.vm.provision "chef_client" do |chef|
			chef.chef_server_url = "#{CHEF_SERVER_PROTOCOL}://#{CHEF_SERVER_IP}:#{CHEF_SERVER_PORT}"
			chef.validation_key_path = "../etc-chef-server/chef-validator.pem"
		end
		
	end

end